spring:

  cache:
    type: redis

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      expire: 60
      password: ${SPRING_REDIS_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

security:
  permissions-policy:
    features:
      geolocation: 'self'
      microphone: ()