spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/youtube
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      expire: 60

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace