spring:

  cache:
    type: redis

  data:
    redis:
      port: ${SPRING_REDIS_PORT}
      host: ${SPRING_REDIS_HOST}
      expire: 60
      password: ${SPRING_REDIS_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

security:
  permissions-policy:
    features:
      geolocation: 'self'
      microphone: ()